### ISSUE TITLE
Compliments & a question!!

### ISSUE THREAD

**Issue by ruohoruotsi** [goodhertz/coldtype#44]
👋  Good day, GoodHertz Gente! 🙇  this is a MAD PROPS & question issue!

First the PROPS &rarr;
I'm a big fan of your plugins 👏 👏 👏 . I own 1/2 the suite, I esp _love_ Vulf Comp, Wow Control, they appear on just about everything [I write](https://www.discogs.com/artist/326567-Ruoho-Ruotsi). I also love my GHz and Dither shirts! So it was to my great surprise and delight to read your blog post about Coldtype!!!

Why am I so excited about a library for programmatic & generative typography? 

- Well, this has been an adjacent passion of mine in addition to music production and running an indie music label. 
- 7 years ago I [wrote about](https://github.com/ruohoruotsi/ruohorecords/tree/master/generative_logotype#readme) my vision for  “living”, “kinetic” typographic constructions as part of my label's visual identity.  
- For my [current label](https://ruohorecords.bandcamp.com/) efforts, I developed [a custom type using p5.js](https://github.com/ruohoruotsi/ruohorecords/blob/master/generative_logotype/p5/RR_BANDCAMP_HEADER/sketch.rr.js), which was very manual even though it was programmatic. 
- Similarly for music videos, png exports of different generative "versions" of the logo, I animate (on the beat) as part of the splash on my music videos ([vid1](https://www.youtube.com/watch?v=M_M1WytD_DA), [vid2](https://www.youtube.com/watch?v=5EG3_jhBLps) & older deprecated logotype &rarr; [vid3](https://www.youtube.com/watch?v=AraSZa0aj7g) )

So given that context, I'm very excited to DIVE INTO Coldtype to see if I can more easily and quickly realize my typographic ideas for videos, annotate my dj mixes, etc etc. I'm not scared to get my hands dirty as the above examples show ..... 

My question is &rarr; I see many of your sketches require an actual font and as I've drawn things on a canvas using p5.js and made individual letters, would you recommend I go the extra mile to make an actual font (.tff) before diving into ColdType? or is there a way to benefit from it in the more freeform way that I've used p5.js?

thank you again and brilliant job! 🙇

**Comment by stenson** [comment]
Thanks for the kind words & for supporting Goodhertz — & for the very interesting questions!

You are correct to point out that a lot of Coldtype uses actual font files. This was one of the motivating factors behind its creation: to create a library that can manipulate existing fonts in complex ways. I think from what you're describing, it sounds like you could definitely benefit from creating an actual font version of the font you've made with p5.js, just in terms of reusability across projects, although I know that making fonts can be a rabbit hole of its own (and it's not particularly easy to get started in that process). I have made some generative code-only fonts using Coldtype myself, although I haven't documented the particular way in which to do that. Hopefully I can get some documentation around that up on the doc site soon.

All that said, from what you've described, I'm not sure I know of a great reason to switch from p5.js to Coldtype, especially if you're enjoying using p5.js. Is there a particular reason you're looking to switch away from p5.js?

**Comment by ruohoruotsi** [comment]
Hi Rob!
thank you for your answers and some great context! Lemme tackle them in order: 

- 💯 ack on the potential rabbit hole for making an actual font. Perhaps if I sandboxed font-making to a few weeks, I could explore the upside
- What's wrong w/ p5.js or why am I looking at alternatives? Well part of it is language preference, I do C/C++/Python for work and have mature dev environments while for Javascript, I'm improvising/slumming it w/ p5 reference, Sublime & command-r in Chrome 😄  Overall JS has been okay to learn but my code seems "too verbose" for do the small things I want ... like draw or animate a capital R. So perhaps  I need to create more "supporting infra" for my desired tasks. 
- In contrast, my interest in Coldtype was peaked when I saw how compact the code using it was and thought if I can bring my font, I can directly start experimenting with text that I want to animate ... plus for "lyrics videos" ... I might not want my label logotype to write lyrics and you already have brilliant examples for all kinds motion & transforms. In p5.js, animation is much more basic and not as type specific ..
- Finally, community ... I don't know anyone else doing this (let alone in p5.js) so thought it could be fun to contribute/test/discuss with others using the same framework.

Re: Font-making, do you have a preferred tool (on MacOS/*nix)?

**Comment by stenson** [comment]
All makes sense! I was just looking into p5 & I didn't realize how un-tuned it was for doing precise frame-by-frame animation, so I guess that's definitely one reason to switch to coldtype. And I'm a big fan of abbreviated idioms in code so there's definitely opportunity to write very short expressive code (maybe too short but who's to say).

I'll try to work up an example over the weekend of making a generative font using coldtype + [defcon](https://defcon.robotools.dev/en/latest/), which is a library that can programmatically edit UFO files, which is the font authoring format I use often in combination with coldtype. I also use the GUI app [RoboFont](https://robofont.com/) (Mac-only), but that can be quite an up-front investment. I know Glyphs is also very good, but unfortunately the "Mini" version of Glyphs doesn't seem to support UFOs as a format (though the full version does). Either way you don't really need a GUI font editor if your goal to is do just generative fonts, but if you are looking to hand-tweak them in a GUI, either RoboFont or Glyphs is the way to go (if you're on Mac — there are some others out there that seem to be pretty good cross-platform, and runebender is an open-source one I've heard of, but I think it's still under active development).

N.B. Defcon is already included in Coldtype and available when you `from coldtype import *` (the `Font` of defcon is then available as the aliased `DefconFont` since there’s a `Font` in coldtype as well).

Also worth noting at a high level — the big upside of Python (to me) is that it's the lingua franca for font-programming (as far as I can tell), so there's lots of code out there to learn from / crib from as you get deeper into font programming / font manipulation.

Will update this thread once I've got a working example of font-generation, but basically the overall architecture is: write a coldtype animation where each frame is a `DATPen` representation of a glyph, i.e. frame 0 is `A`, frame 1 is `B`, etc., then you can render that animation into into serialized .pickle files (by setting `fmt="pickle"` on the @animation decorator), then you write a `def release(_)` in your coldtype source file that deserializes all the individual pickle files into `defcon.Glyph` objects (via the `.to_glyph()` method on `DATPen`) into a single DefconFont via the `.insertGlyph` function. Finally I use fontmake to turn the UFO file into, usually, an .otf font file, though .ufo files can be loaded directly in Coldtype, so that's an unnecessary step if your goal is to then use the generated font just in a coldtype script. Lots (tons) of details glossed over there, but thought it might be useful (for myself and anyone reading this) to outline it here off the top of my head.

I think in general learning about how fonts are made is super useful, since the font format can be used for all kinds of things, not just letters (I use .ufo files to catalog logos for Goodhertz, for instance).

**Comment by ruohoruotsi** [comment]
Brilliant!  WOW! thanks sooo much for taking the time to make an example 🙇 🙏  It's like I just opened the door to a candy store full delights & tasty opportunities!

Cool, I'm checking out defcon and the UFO format details now, and I'll queue up download & evals of Robotfont & Glyphs to see which I should invest in! Thanks! I don't think I would have found these by googling! 😄  I like the idea of being multifariously manual AND programmatic 😸 as part of my font-creation deep-dive.

**Comment by stenson** [comment]
Cool! Here’s the full code for a script to generate the glyphs space + ABC, write those glyphs to a UFO, and then preview that UFO file. I'll admit this ended up being a little longer than I expected, and most of it could be abstracted away into a library (potentially as part of Coldtype itself), but it's nice to know that all you need for a full generative font workflow is ~150 lines of Coldtype + the code for the actual generative font glyphs. (This code is also now in the coldtype repo in the examples directory: https://github.com/goodhertz/coldtype/blob/main/examples/generative_font.py)

```python
import datetime
from subprocess import run

from coldtype import *
from coldtype.pens.dattext import DATText

cap_height = 750
descender = -250
font_name = "Generative"
style_name = "Regular"

# decorator class to wrap glyph-building functions

class glyphfn():
    def __init__(self, width=1000, lsb=0, rsb=0):
        """lsb = left-side-bearing / rsb = right-side-bearing"""
        self.lsb = lsb
        self.rsb = rsb
        self.frame = Rect(width, cap_height)
        self.bbox = Rect(lsb + width + rsb, cap_height)
    
    def __call__(self, func):
        self.func = func
        self.glyph_name = func.__name__
        self.unicode = glyph_to_uni(self.glyph_name)
        return self

# !!! the important part:
# individual functions to draw glyphs
# the function names should be canonical
# "glyphNames" as in assets/glyphNamesToUnicode.txt

@glyphfn(300)
def space(r):
    return DP() # i.e. nothing (since it's a blank space)

@glyphfn(500, 10, 10)
def A(r):
    return (DATPen()
        .rect(r)
        .difference(DP(r.take(100, "mdy")
            .take(20, "mdx")
            .offset(0, 100)))
        .difference(DP(r.take(200, "mny")
            .take(20, "mdx"))))

@glyphfn(500, 10, 10)
def B(r):
    t, b = r.inset(0, 100).subdivide(2, "mxy")
    return (DATPen()
        .rect(r)
        .difference(DP(t.take(100, "mdy")
            .take(20, "mdx")))
        .difference(DP(b.take(100, "mdy")
            .take(20, "mdx")))
        .difference(DP(r.take(100, "mdy")
            .take(100, "mxx"))
            .rotate(45)
            .translate(50, 0)))

@glyphfn(500, 10, 10)
def C(r):
    return (DATPen()
        .rect(r)
        .difference(DP(r.take(20, "mdx")
            .inset(0, 250)))
        .difference(DP(r.take(0.5, "mxx")
            .take(20, "mdy"))))

# !!! end of glyph drawing functions

def find_glyph_fns():
    found = []
    itms = globals().items()
    for k, v in itms:
        if isinstance(v, glyphfn):
            found.append(v)
    return found

glyph_fns = find_glyph_fns()

# our useable output is a UFO file,
# which we should make sure exists
ufo_path:Path = __sibling__("generative_font.ufo")
if not ufo_path.exists():
    ufo = DefconFont()
    ufo.save(ufo_path)

def show_grid(render, result):
    if False: # flip to true if you don't want to see the grid
        return result

    gfn = result[0].data.get("gfn")
    if not gfn:
        print("! No glyph found")
    else:
        bbox = gfn.bbox.offset(0, 250)
        return DATPens([
            DATPens(result).translate(0, 250),
            DATPen().gridlines(render.rect).s(hsl(0.6, a=0.3)).sw(1).f(None),
            (DATPen()
                .line(bbox.es.extr(-100))
                .line(bbox.en.extr(-100))
                .line(bbox.ee.extr(-100))
                .f(None).s(hsl(0.9, 1, a=0.5)).sw(4)),
            (DATText(gfn.glyph_name, Style("Times", 48, load_font=0),
                render.rect.inset(50)))
        ])

preview_frame = Rect(1000, (-descender*2)+cap_height)

@animation(preview_frame, timeline=Timeline(len(glyph_fns)), postfn=show_grid)
def glyph_viewer(f):
    glyph_fn = glyph_fns[f.i]
    
    ufo = DefconFont(ufo_path)
    ufo.info.familyName = font_name
    ufo.info.styleName = style_name
    ufo.info.capHeight = cap_height
    ufo.info.ascender = cap_height
    ufo.info.descender = descender
    ufo.info.unitsPerEm = 1000

    print(f"> drawing :{glyph_fn.glyph_name}:")
    glyph_pen = glyph_fn.func(glyph_fn.frame).f(0)

    # shift over by the left-side-bearing
    glyph_pen.translate(glyph_fn.lsb, 0)
    glyph = glyph_pen.to_glyph(
        name=glyph_fn.glyph_name,
        width=glyph_fn.frame.w + glyph_fn.lsb + glyph_fn.rsb,
        allow_blank = True)
    glyph.unicode = glyph_to_uni(glyph_fn.glyph_name)
    ufo.insertGlyph(glyph)
    ufo.save()
    return glyph_pen.add_data("gfn", glyph_fn)


@renderable((1080, 300))
def font_previewer(r):
    """
    This function loads the ufo that’s been created by the code
    above and displays it "as a font" (i.e. it compiles the ufo
    to a font and then uses the actual font to do standard font-
    display logic)
    """
    ufo = Font(ufo_path)
    return (StyledString("ABC CBA",
        Style(ufo, 150))
        .pens()
        .align(r)
        .f(0))

# to run this code, go to the viewer
# app while it’s running, then hit cmd+l
# N.B. you'll need to have `fontmake`
# available in your virtualenv, which
# should be as easy as `pip install fontmake`
# with the virtualenv activated

def release(_):
    ufo = DefconFont(ufo_path)
    date = datetime.datetime.now().strftime("%y%m%d%H%M")
    font_name = "_".join([
        ufo.info.familyName.replace(" ", ""),
        ufo.info.styleName.replace(" ", ""),
        date
    ])
    fontmade_path = ufo_path.parent / f"fontmakes/{font_name}.otf"
    fontmade_path.parent.mkdir(exist_ok=True)
    run([
        "fontmake",
        "-u", str(ufo_path),
        "-o", "otf",
        "--output-path=" + str(fontmade_path)])
```

If you run it in a coldtype virtual environment in the coldtype rep itself, the command would be `coldtype examples/generative_font.py` and then an app should pop up on your screen and display something like this:

![image](https://user-images.githubusercontent.com/89770/118372852-72ab7e80-b568-11eb-8f0a-91268ad051df.png)

To change glyphs, you just need to hit the arrow keys in the coldtype app while it's running.

I also realized, if you'd rather skip buying a full font editor & you just want to view a UFO in a GUI, then the free app [FontGoggles](https://fontgoggles.org/) fits the bill, and you should be able to drag the UFO created by the script from Finder directly into FontGoggles & it should show up like this (if you type in "ABC" in the top bar).

![image](https://user-images.githubusercontent.com/89770/118372859-77703280-b568-11eb-8b12-3c5f2b1d92e5.png)

Obviously there's a lot going on in that script — happy to answer any & all questions about it.

**Comment by ruohoruotsi** [comment]
Amazing!!! 🙇 🙏 Thank you SO much for this amazing response and snippet, as well as the consideration about FontGoogles!!! 
I'm gonna get going on this week and will report back. My sense after spending some time w/ Robofont & Glyphs is that I'm gonna spring for those when my 30-day trial is up 😄 🚀 So I'll keep a bg thread on generalized font-science-learning while looking towards getting handy with Coldtype for my living logotype & animation needs!

BTW, I also saw somewhere on your social, your recommendation for "python for designers", so thanks for that too!  👏 👏
