### ISSUE TITLE
Coldtype App Icon is Blurry

### ISSUE THREAD

**Issue by tallpauley** [goodhertz/coldtype#5]
OS: macOS Catalina (Version 10.15.1)
App Version: 0.0.1 (0.0.1)

Let me know if I can provide you with any more information. Just figured I'd report things as they come up, whether they are important at this point or not.

![Screen Shot 2020-06-23 at 9 30 30 AM](https://user-images.githubusercontent.com/7945233/85430100-86a35780-b534-11ea-9ff7-2e351d93ebe0.png)

![Screen Shot 2020-06-23 at 9 30 13 AM](https://user-images.githubusercontent.com/7945233/85430108-8905b180-b534-11ea-966d-2e010783dd19.png)

**Comment by tallpauley** [comment]
<img width="207" alt="Screen Shot 2020-06-23 at 7 35 37 PM" src="https://user-images.githubusercontent.com/7945233/85491674-cbf17480-b588-11ea-9475-08dcdf8fc1da.png">

Strangely this seems to have resolved itself. Though I do wonder why at first it had the low-res CT icon.

**Comment by stenson** [comment]
Closing since the coldtype-viewer app no longer exists (GUI is now an integrated part of the python CLI process), but thanks for the report!

**Comment by tallpauley** [comment]
No problem! Excited where you're taking this with Skia support!
