### ISSUE TITLE
Problem with PyOpenGL-accelerate

### ISSUE THREAD

**Issue by szymonhernik** [goodhertz/coldtype#64]
Hi, running into a problem like this, both when setting up a virtual environment for python 3.9 and 3.8. Installing PyOpenGL-accelerate gives me the same error so I'm guessing it's something to do with the dependence on this package. Any other way I can try installing coldtype? 

Thanks, Szymon

Installing collected packages: PyOpenGL-accelerate, noise, glfw, coldtype
    Running setup.py install for PyOpenGL-accelerate ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/szymonhernik/venv/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/57/6l441ljd72sg9kmq2wmdy_r40000gn/T/pip-install-3qqf30sg/pyopengl-accelerate_1cb726cbe92b4005861cec5fdab18249/setup.py'"'"'; __file__='"'"'/private/var/folders/57/6l441ljd72sg9kmq2wmdy_r40000gn/T/pip-install-3qqf30sg/pyopengl-accelerate_1cb726cbe92b4005861cec5fdab18249/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/57/6l441ljd72sg9kmq2wmdy_r40000gn/T/pip-record-bn058k1w/install-record.txt --single-version-externally-managed --compile --install-headers /Users/szymonhernik/venv/include/site/python3.9/PyOpenGL-accelerate
         cwd: /private/var/folders/57/6l441ljd72sg9kmq2wmdy_r40000gn/T/pip-install-3qqf30sg/pyopengl-accelerate_1cb726cbe92b4005861cec5fdab18249/
    Complete output (14 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.9-universal2-3.9
    creating build/lib.macosx-10.9-universal2-3.9/OpenGL_accelerate
    copying OpenGL_accelerate/__init__.py -> build/lib.macosx-10.9-universal2-3.9/OpenGL_accelerate
    running build_ext
    building 'OpenGL_accelerate.wrapper' extension
    creating build/temp.macosx-10.9-universal2-3.9
    creating build/temp.macosx-10.9-universal2-3.9/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -arch arm64 -arch x86_64 -g -I/private/var/folders/57/6l441ljd72sg9kmq2wmdy_r40000gn/T/pip-install-3qqf30sg/pyopengl-accelerate_1cb726cbe92b4005861cec5fdab18249/.. -I/private/var/folders/57/6l441ljd72sg9kmq2wmdy_r40000gn/T/pip-install-3qqf30sg/pyopengl-accelerate_1cb726cbe92b4005861cec5fdab18249/src -I/private/var/folders/57/6l441ljd72sg9kmq2wmdy_r40000gn/T/pip-install-3qqf30sg/pyopengl-accelerate_1cb726cbe92b4005861cec5fdab18249 -I/Users/szymonhernik/venv/include -I/Library/Frameworks/Python.framework/Versions/3.9/include/python3.9 -c src/wrapper.c -o build/temp.macosx-10.9-universal2-3.9/src/wrapper.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/szymonhernik/venv/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/57/6l441ljd72sg9kmq2wmdy_r40000gn/T/pip-install-3qqf30sg/pyopengl-accelerate_1cb726cbe92b4005861cec5fdab18249/setup.py'"'"'; __file__='"'"'/private/var/folders/57/6l441ljd72sg9kmq2wmdy_r40000gn/T/pip-install-3qqf30sg/pyopengl-accelerate_1cb726cbe92b4005861cec5fdab18249/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/57/6l441ljd72sg9kmq2wmdy_r40000gn/T/pip-record-bn058k1w/install-record.txt --single-version-externally-managed --compile --install-headers /Users/szymonhernik/venv/include/site/python3.9/PyOpenGL-accelerate Check the logs for full command output.

**Comment by stenson** [comment]
Hi Szymon — sorry the install didn't work!

Are you using OSX 10.9? (Looks like you might be from the error print-out, though I'm not sure). If you are, I think some of the packages Coldtype relies on don't have pre-built binaries for OS's going back that far, so you'd either need to install or update Xcode (and potentially the Xcode command line tools), or upgrade the OS to something more recent (which obviously you might have a good reason not to).

**Comment by stenson** [comment]
Alternatively, if you want to avoid installing things, you can use Coldtype in an environment like Google Colab, as demonstrated here: https://twitter.com/coldtypexyz/status/1427323974300540945

I haven't documented that part of the library well yet, but hopefully will in the near future.

**Comment by szymonhernik** [comment]
Hi Rob, thanks for such a quick response.

So I'm running on Big Sur 11.5. and Xcode 11.4 so I'm guessing everything should be up to date.

**Comment by stenson** [comment]
Huh, yeah I don't know what the particular issue there might be. I did just look at why exactly PyOpenGL-accelerate is a required dependency, and the answer is: I'm not quite sure! From some preliminary tests, it looks like Coldtype can function without it, so you could try installing the packages manually to avoid PyOpenGL-accelerate and see if everything else installs correctly, you'd just have to do run each of these lines individually in your virtualenv (kind of a pain, but shouldn't take that long)

```
pip install coldtype
pip install glfw
pip install PyOpenGL
pip install "skia-python==86.1"
pip install skia-pathops
pip install SimpleWebSocketServer
pip install "watchdog<2.0.0"
pip install ufo2ft
pip install numpy
```

Let me know if that works/doesn't — I'll look more into why PyOpenGL-accelerate is included (it was added to Coldtype a long time ago), and if it isn't necessary anymore I can remove it from the [viewer] dependencies.

**Comment by stenson** [comment]
Looks like it was kind of a superfluous addition to the requirements, so the latest version `0.6.9` has this removed. So you shouldn't have to try it with all those manual installs, and could instead just do `pip install coldtype[viewer]==0.6.9` to see if it works now

**Comment by stenson** [comment]
@szymonhernik any luck with that change? 0.7.0 is the current version as of this writing and PyOpenGl-accelerate has been removed, so I'm going to close the issue for now — feel free to open again if the issue persists tho
