### ISSUE TITLE
glyphwise more than two lines

### ISSUE THREAD

**Issue by jo-lang** [goodhertz/coldtype#68]
```Glyphwise``` is super nice to use. it even works when there is one newline (```\n```) in the text. however if there are more than two lines every following line gets the same values as the second line.

**Comment by stenson** [comment]
thanks for the report! hard to believe I've never tried to use 3 lines of text in a Glyphwise! — fixed on `main` now, had fun trying out a three-line `Glyphwise`

Thought I'd drop in the investigation code here for posterity:

from coldtype import *

```python
@animation((1080, 540), timeline=30, bg=0, render_bg=1)
def scratch(f):
    def styler(g):
        return Style(Font.MutatorSans(), 120,
                wdth=f.adj(-g.i*25).e("eeio", 1))
    
    return (Glyphwise("THREE\nLINE\nTEXT", styler)
        .track(30, v=1)
        .xalign(f.a.r, th=1)
        .align(f.a.r, th=1)
        .f(1))

release = scratch.export("gif")
```

![scratch](https://user-images.githubusercontent.com/89770/136677941-21d5a8f5-dc83-4172-aa6d-32f8f8809b2a.gif)
