### ISSUE TITLE
windows file monitoring (watchdog) doesn't seem to be working

### ISSUE THREAD

**Issue by ejlmljt** [goodhertz/coldtype#86]
the   last  line is FileNotFoundError: [WinError 2] The system cannot find the file specified.  
when  run from  C:\Users\XXXX\Documents>coldtype demo
I  tried   6 or 7 other  demo files and usually got this  error  but sometimes  get  nothing  displayed.
Last
 File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\watchdog\utils\__init__.py", line 110, in start
    self.on_thread_start()
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\watchdog\observers\read_directory_changes.py", line 68, in on_thread_start
    self._handle = get_directory_handle(self.watch.path)
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\watchdog\observers\winapi.py", line 276, in get_directory_handle
    return CreateFileW(path, FILE_LIST_DIRECTORY, WATCHDOG_FILE_SHARE_FLAGS,
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python39\lib\site-packages\watchdog\observers\winapi.py", line 115, in _errcheck_handle
    raise ctypes.WinError()
FileNotFoundError: [WinError 2] The system cannot find the file specified.

**Comment by stenson** [comment]
should be fixed now in coldtype==0.8.2 (will need a `pip install "coldtype[viewer]" --upgrade`)

**Comment by stenson** [comment]
Hi Eugene — thanks for trying that out! I've just been testing on Windows and looking into the file-watching behavior a little more. The error you're seeing makes sense (and isn't a big issue, as it doesn't involve normal use of coldtype), though I think this deserves more attention, as I couldn't get the updating-on-file-save to work on Windows at all, so I'm going to reopen this and change the title.

**Comment by stenson** [comment]
i've removed the watchdog dependency completely in the latest release (0.9.0), should file-watching should be fixed now on windows

**Comment by ejlmljt** [comment]
Thanks  Rob,

I upgraded  the installation  and did  a quick  check.  I  ran   "coldtype
demo"    .  The   coldtype  frame  displayed  and there  were  no error
messages in the cmd window.
Have a  great day.
Eugene

**Comment by stenson** [comment]
thanks for trying it out!
