### ISSUE TITLE
import  os.uname  not  found  in  Windows 10,  python 3.9  https://bugs.python.org/issue8080

### ISSUE THREAD

**Issue by ejlmljt** [goodhertz/coldtype#87]
Hello, I  really like  this   project but am  having trouble on  windows.
I installed  coldtype  globally with 
pip   install coldtype[viewer]
I    received   an  error message  on   os.uname   from __init__.py
I  changed the source  but   am now receiving a  file not  found   error   as  described in my other message.

**import platform**

# source: https://github.com/ PixarAnimationStudios/USD/issues/1372

def monkeypatch_ctypes():
    import ctypes.util, platform
    uname = **platform.**uname()
    if uname.**system** == "Darwin" and uname.release >= "20.":

**Comment by stenson** [comment]
thanks for reporting this! should be fixed now in coldtype==0.8.2 (will need a `pip install "coldtype[viewer]" --upgrade`)
